CREATE TABLE CLIENTES (ID_USUARIO INT (100) NOT NULL,
NOMBRE VARCHAR (100) NOT NULL,
DESCRIPCION VARCHAR (100) NULL,
CONTRASEÑA VARCHAR (100) NOT NULL,               
MEDICAMENTOS VARCHAR (100)NOT NULL,
FOTO_PERFIL BLOB NULL,
PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE MEDICAMENTOS( ID_MEDICAMENTO INT NOT NULL,
                         USUARIO_CORRESPONDIENTE INT NOT NULL,
                          NOMBRE VARCHAR NOT NULL,
                          FECHA_INICIO DATE NULL,
                          FECHA_FINAL DATE NULL,
                          DOSIS VARCHAR NOT NULL,
                          HORARIO TIME NULL,
                          FECHA_VENCIMIENTO DATE NOT NULL,
                          PRIMARY KEY (ID_MEDICAMENTO),
                          FOREIGN KEY (USUARIO_CORRESPONDIENTE) REFERENCES CLIENTES(ID_USUARIO)
);
