CREATE  DATABASE CALENDARIO_MED;

USE CALENDARIO_MED

CREATE TABLE USUARIO(NOMBRE_US VARCHAR(30) NOT NULL, PASSWORDS VARCHAR (30) NOT NULL, PRIMARY KEY(NOMBRE_US));

INSERT INTO TABLE USUARIO ("TOMAS", "123ÆSIR456");

CREATE TABLE MEDICAMENTO(ID_MED INT NOT NULL,
   NOMBRE_US VARCHAR (30) NOT NULL,MED VARCHAR(50) NOT NULL, DOSIS VARCHAR(50) NOT NULL, 
   FECHA_IN DATE(50) NOT NULL, FECHE_FIN DATE(50) NULL,
   FECHA_VENCI DATE(50) NULL, PRIMARY KEY(ID_MED),
   FOREIGN KEY (NOMBRE_US) REFERENCES USUARIO(NOMBRE_US));
